### ISSUE TITLE
Where is the ImageNet pretrained classification models?

### ISSUE THREAD

**Issue by yzou2** [TuSimple/TuSimple-DUC#1]
In the link to the models (https://drive.google.com/drive/folders/0B72xLTlRb0SoREhISlhibFZTRmM), I can only find the segmentation pretrained models. Would you please tell me where can I find the classification model pretrained on ImageNet?

**Comment by wpqmanu** [comment]
You could use any publicly available pretrained ResNet model using MXNet, such as the ones [here](https://github.com/tornadomeet/ResNet). You can refer to our [symbol](https://github.com/TuSimple/TuSimple-DUC/tree/master/tusimple_duc/networks) to match the name of the layers. Or to get a quicker start, you could use the [pretrained DeepLab V2 caffe model](http://liangchiehchen.com/projects/DeepLabv2_resnet.html) and convert it to the MXNet format.

**Comment by shipeng-uestc** [comment]
Hi, I didn't install caffe . For quickly to train, can anyone share the pretrained Resnet model that converted from deeplab v2 caffe model?@yzou2@wpqmanu Thanks.
One more question.How to match the name of layers of your symbol?
Thanks.

**Comment by shipeng-uestc** [comment]
Hi , I found init.params. Is it the pretrained Resnet model that converted from deeplab v2 caffe model? @wpqmanu

**Comment by wpqmanu** [comment]
Yes
