### ISSUE TITLE
ImageNet Pretrained ResNet-101 Model

### ISSUE THREAD

**Issue by ArsenLuca** [TuSimple/TuSimple-DUC#11]
I tried to convert the deeplab model in #1, but failed due to error 
         Message type "caffe.ImageDataParameter" has no field named "label_type"
So would you please share the ImageNet pretrained ResNet-101 Model please? 
Thanks

**Comment by wpqmanu** [comment]
We just uploaded the deeplab model (parameters) on [Google Drive](https://drive.google.com/drive/u/1/folders/0B72xLTlRb0SoREhISlhibFZTRmM). You can create the symbol by referring to the deeplab caffe prototxt or by modifying our symbol.

**Comment by ArsenLuca** [comment]
@wpqmanu thx

**Comment by yzou2** [comment]
@wpqmanu According to [Google Drive Readme] (https://docs.google.com/document/d/1v-aIcV5aZZ8JtpP1r5-HaO9a8JF-zqig90S6N6Ws4ME/edit), the init model is the Cityscapes pretrained DeepLab v2. Would you kindly share the DeepLab v2 model converted from the ImageNet pretrained ResNet-101 model? Thanks a lot.
