### ISSUE TITLE
About make/congfig.mk in anaconda 

### ISSUE THREAD

**Issue by pandamax** [TuSimple/TuSimple-DUC#12]
Hello,I am very interested in your project.But I am a newbie.I have a question to ask for your help.I have installed mxnet_cu90==0.12.1 in  anaconda env.and I use ubuntu16.04 ,cuda9.0 and cudnn7.0 .How  should I modify the original make/config.mk that you provided? Thanks a lot!

**Comment by wpqmanu** [comment]
The  make/config.mk file is in relative to the mxnet root directory
