### ISSUE TITLE
how to set the val.lst

### ISSUE THREAD

**Issue by CarryJzzZ** [TuSimple/TuSimple-DUC#15]
Hi,_ when i use predict_full_image.py , I make my val.lst like this:
    
![111](https://user-images.githubusercontent.com/26374380/34149062-c5e963e0-e4de-11e7-88cf-2c6c79654504.png)
/home/xxx/MXnetProjects/TuSimple-DUC/Data/cityscapes/gtFine/test/berlin/berlin_000000_000019_leftImg8bit.png_`
But these is always a error, i debug it and found that this is a error when use im = cv.imread(img_path)[:, :, ::-1] in predict_single, for i set the vla.lst in wrong format.
can you help me.
THANKS!

**Comment by GrassSunFlower** [comment]
The list can be something like 
`index \t relative_img_path \t relative_label_path`
And the full paths of images of ground truths are concatenated by 'test_img_dir' and 'gt_dir' in the config file respectively.

**Comment by CarryJzzZ** [comment]
thanks! it works! and your  head portrait of "liu xing" is interesting

**Comment by shipeng-uestc** [comment]
Hi，@CarryJzzZ。
Can you share me your code for making val.lst?
Thanks.
A baiduyun link.

**Comment by shipeng-uestc** [comment]
I have solve it. Thanks。
