### ISSUE TITLE
How to apply CRFs?

### ISSUE THREAD

**Issue by reborm** [TuSimple/TuSimple-DUC#18]
Hi, I feel confused to CRFs. I'm sorry that i can't find the way you apply the CRFs to your ResNet-DUC. Could you please tell me how to do it? Thank you very much!!!!

**Comment by wpqmanu** [comment]
We did not apply CRFs in the current release. Instead We applied multi-scale testing instead. To try CRF, you can refer to [the pydensecrf repo](https://github.com/lucasb-eyer/pydensecrf)

**Comment by reborm** [comment]
The link you sent is very helpful !  Thank you very much
