### ISSUE TITLE
Where to find the train-list "train_bigger_patch.lst"

### ISSUE THREAD

**Issue by thomasdic2000** [TuSimple/TuSimple-DUC#2]
I tried to use the default 'imglists/train.lst,' but seems format not recognized. Could you please provide the train-list you used? Thanks.

**Comment by GrassSunFlower** [comment]
You can try using data_prep/get_cityscapes_list.py to generate the data list

**Comment by acgtyrant** [comment]
@GrassSunFlower How to decide `image_path` and `label_path` in `get_cityscapes_list.py`?

As my understanding to this file, I should pass some arguments as below:

```
root = '/home/acgtyrant/BigDatas/Cityscapes'
image_path = 'leftImg8bit/train'
label_path = 'gtFine/train'
```

And `cityscaples_loader.read_data` will read the full image path and label path as `item[0]` and `item[1]`.

However, `utils.get_single_image_duc` will still join `item[0]` and `data_dir` again while the `item[0]` is the full path already, the same for `item[1]`.

**Comment by GrassSunFlower** [comment]
Yes, it is working this way. 
You can try change the content of `data_dir` into something like `.` or modify the output of the `get_cityscapes_list` output.
