### ISSUE TITLE
Do you use Synchronized Batch normalization?

### ISSUE THREAD

**Issue by acgtyrant** [TuSimple/TuSimple-DUC#23]
If so, does your open MXNet support it?

**Comment by Lyken17** [comment]
To my best knowledge, MXNet hasn't supported synchronized Batch Normalization yet. So the same as this project.

Unlike PSP, even without synchronized batch normalization, it is easy to reproduce DUC with meanIoU of 80.2 on cityscape dataset.

If you do want avoid the affect of unsynchronized batch normalization, a simple trick is to reduce the image size and increase the batch size. (Or purchase more fancy GPUs

**Comment by GrassSunFlower** [comment]
Synchonized Batch Normalization is currently not supported by MxNet.
