### ISSUE TITLE
Fail to use other gpus except gpus =0

### ISSUE THREAD

**Issue by Serian1992** [TuSimple/TuSimple-DUC#25]
Hi,

I tried to reset the parameter 'gpus = 3', an error appeared (seen in the fig below). My current environment is Python 2.7, Mxnet version 1.0.0 under Win10 with 4 available GPUs. Any suggestion for this problem? Thanks a lot!
![b06d7a61ad612b7e3edf2f2678936496](https://user-images.githubusercontent.com/27217886/35292861-d6346bc4-003f-11e8-819e-6d0888da3ad0.jpg)

**Comment by GrassSunFlower** [comment]
Actually what you provide in the figure has nothing to do with the error message but some normal message   logged by mxnet. Can you provide the exact error message?
Besides, I would recommend you to try run some basic mxnet examples with gpu No.3 to make sure everything is OK with your hardware, driver and MxNet.
