### ISSUE TITLE
What is the `test_scales` in multiple scale testing？

### ISSUE THREAD

**Issue by acgtyrant** [TuSimple/TuSimple-DUC#28]
I would like to use your open model to reproduce this evaluation:

> ResNet101-DUC-HDC on CityScapes testset (mIoU): 80.1(multiple scale testing )

But I do not know what `test_scales` does you use in `test_full_image.cfg`, could you tell me? Thank you very much.

**Comment by wpqmanu** [comment]
It should be 0.5, 0.75, 1, 1.25, 1.5, and 2

**Comment by acgtyrant** [comment]
I think it may be  `0.5, 0.75, 1, 1.25, 1.5, and 1.75` while PSPNet, deeplab-v3, EncNet and drn all use these scales.
