### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Youngkl0726** [TuSimple/TuSimple-DUC#30]
Why the num_filter in the "res1_3 = Conv_BN_AC(data=res1_2, num_filter=128, kernel=(3, 3), name='conv1_3_3x3', suffix='conv1_3_3x3', pad=(1, 1), stride=(1, 1))", which is in the resnet.py, is 128? 
I think it may be 64.

**Comment by wpqmanu** [comment]
There is no specific reason for setting the number. You can try both.
