### ISSUE TITLE
A issue during trainning the network.

### ISSUE THREAD

**Issue by luyunxi** [TuSimple/TuSimple-DUC#31]
Afer I run the following code ,  the network can not be trainned.
python train_model.py ../configs/train/train_cityscapes.cfg
shown as following:
sipl@sipl:~/lyx/TuSimple-DUC/train$ /usr/bin/python train_model.py ../configs/train/train_cityscapes.cfg
[19:35:52] src/nnvm/legacy_json_util.cc:153: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
sipl@sipl:~/lyx/TuSimple-DUC/train$

**Comment by GrassSunFlower** [comment]
Perhaps you can try the mxnet version as in the submodule.
