### ISSUE TITLE
Data prep script

### ISSUE THREAD

**Issue by DSLituiev** [TuSimple/TuSimple-DUC#32]
I am trying to understand your pipeline so that I can run it on my own data. 
I see a script in `data_prep/get_cityscapes_list.py` but I cannot find from your readme how to run it. 
Can you please add a description of the expected format and/or document the data prep pipeline?
Thank you

**Comment by li-pengcheng** [comment]
I'd also like to know how to use the file, if U know any thing about it, please contact me...

**Comment by GrassSunFlower** [comment]
@DSLituiev Sorry for the late reply. This script is used for doing pre-processing the cityscapes semantic dataset. So you can download the dataset and fill in the corresponding arguments to see the formats of data lists for training. To be more specific, the data list is like lines of all the training data. Each line represents a (image, label) pair with its designated cropping areas for random cropping.

So the format should be something like
[Index] [Image Path] [Label Path] [Cropping Center Y(of height)] [Cropping Center X(of width)].

Also thanks @lpengc for your help.

If you have any other problems, feel free to leave it here.
