### ISSUE TITLE
Could not read from remote repository.

### ISSUE THREAD

**Issue by meanmee** [TuSimple/TuSimple-DUC#33]
git clone --recursive git@github.com:TuSimple/mxnet.git
Cloning into 'mxnet'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by wpqmanu** [comment]
Please try https. https://github.com/TuSimple/TuSimple-DUC.git
