### ISSUE TITLE
crf

### ISSUE THREAD

**Issue by zebinc0409** [TuSimple/TuSimple-DUC#37]
hello,in the paper you have mentioned crf as a post processing procedure,but i couldnt found it on the project,can you provide it

**Comment by wpqmanu** [comment]
Hello, we replaced CRF with multiscale testing in the released code as they have similar performance. If you are interested in using CRF, you can refer to this repo: https://github.com/lucasb-eyer/pydensecrf . We applied their code in our CRF experiments.
