### ISSUE TITLE
How much GPU memory is required

### ISSUE THREAD

**Issue by amiltonwong** [TuSimple/TuSimple-DUC#5]
Hi, authors,

How much GPU memory is required, in training and prediction, respectively?
Does a 6GB GPU card meet the requirement?

THX!

**Comment by GrassSunFlower** [comment]
It depends on your patch size and way of usage. In terms of training, a 320*320 patch with batch size 1 should take about 3GB. As for testing, a full resolution of 2048 * 1024 should take above 6GB GPU memory. So if you want to get better results, I would highly recommend you use a GPU with more than 8GB memory.
